version: '3'

services:
  # Service pour l'application React
  react-app:
    container_name: react-app
    build:
      context: ./App
      dockerfile: Dockerfile # Assurez-vous de créer un Dockerfile approprié dans le dossier 'App'
    ports:
      - "3000:3000" # Vous pouvez ajuster le port selon vos besoins

  # Service pour le serveur Node (API Nest)
  nest-api:
    container_name: nest-api
    build:
      context: ./server
      dockerfile: Dockerfile 
    ports:
      - "8000:8000"
    depends_on:
      - database

  # Service pour la base de données MySQL
  database:
    container_name: mysql-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cook
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./Data:/var/lib/mysql
